Support dropout
NeuralNetworkVerification/Marabou pull request #774
Opened 2024-03-04 19:30 UTC by wu-haoze

2024-03-05 05:19 UTC, MatthewDaggitt requested changes
I don't think that always throwing this off to the identity node parsing is a good approach as we might (silently!) incorrectly parse the network when the `training_mode` input is set to true. 
Looking at the [documentation](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Dropout), we should test for the presence of the third input, and throw a meaningful user error if it is set to true. Only if it is not present, or set to false should we delegate to parsing it as an identity.

2024-03-05 20:02 UTC, wu-haoze commented
> I don't think that always throwing this off to the identity node parsing is a good approach as we might (silently!) incorrectly parse the network when the `training_mode` input is set to true. Looking at the [documentation](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Dropout), we should test for the presence of the third input, and throw a meaningful user error if it is set to true. Only if it is not present, or set to false should we delegate to parsing it as an identity node.

Sure. For that, I extended the OnnxParser a little further to handle Int32, since Bool is internally stored as that according to [this](https://github.com/onnx/onnx/blob/606ee9df9580872e34701791b8fbe433cefa6916/onnx/onnx.proto3#L576-L583)  (is this the right file to look at?)

2024-03-06 03:03 UTC, MatthewDaggitt requested changes

2024-03-06 03:27 UTC, wu-haoze commented on resources/onnx/test_dropout.onnx
The file is used in maraboupy/test/test_onnx.py to pass the python code coverage test. I tried to use the dropout unit models in the model zoo but on the CI, onnxruntime throws an error on those layer zoo models for python version 3.8 for some reason. I think this should be fixed in a separate PR. Perhaps some further amendment to the onnx_layer_zoo.py is needed.

2024-03-06 03:27 UTC, wu-haoze commented on resources/onnx/layer-zoo/onnx-layer-zoo.py
> +    network_dir = os.path.join(output_dir ,f"{name}.onnx")
Changed to network_path

2024-03-06 03:32 UTC, wu-haoze commented on resources/onnx/test_dropout.onnx
See this run https://github.com/NeuralNetworkVerification/Marabou/actions/runs/8147526449/job/22270758583
I spent some effort fixing the issue but to no avail. :(

2024-03-11 01:26 UTC, MatthewDaggitt approved these changes

2024-03-11 01:26 UTC, MatthewDaggitt commented on resources/onnx/test_dropout.onnx
Okay fair enough. We should probably open an issue for that...

2024-03-11 06:00 UTC, merged