Implement BaBSR Branching Heuristic as a new Branching Strategy
NeuralNetworkVerification/Marabou pull request #851
Opened 2024-12-11 18:13 UTC by liamjdavis

This pull request introduces a new branching strategy, the BaBSR branching heuristic. The new change for this new heuristic includes additions to the configuration, option parsing, and engine components.

Key changes include:

### Branching Strategy Implementation:
* Implemented the `pickSplitPLConstraintBasedOnBaBsrHeuristic` method in the `Engine` class to split on the ReLUs with the highest BaBSR score. [[1]](diffhunk://#diff-792e7ee9541fb28c61cdf063f032057c64c788f41fe955bae6b5c1a702f2f15bR2707-R2777) [[2]](diffhunk://#diff-792e7ee9541fb28c61cdf063f032057c64c788f41fe955bae6b5c1a702f2f15bR2889-R2890) [[3]](diffhunk://#diff-792e7ee9541fb28c61cdf063f032057c64c788f41fe955bae6b5c1a702f2f15bL2840-R2915)
* Added support for BaBSR heuristic in the `ReluConstraint` class, including methods to compute the BaBSR score. [[1]](diffhunk://#diff-27f5511cb7c908af7f4eb425c70e8631c1216d3a2214b404a3c3e3c611347751R1022-R1026) [[2]](diffhunk://#diff-27f5511cb7c908af7f4eb425c70e8631c1216d3a2214b404a3c3e3c611347751R1037-R1087) [[3]](diffhunk://#diff-27f5511cb7c908af7f4eb425c70e8631c1216d3a2214b404a3c3e3c611347751R1111-R1115) [[4]](diffhunk://#diff-8915782f096b5bc75054300aa7240a7b18b4b40a97c5cf3f79edb8530b892932R40-R48) [[5]](diffhunk://#diff-8915782f096b5bc75054300aa7240a7b18b4b40a97c5cf3f79edb8530b892932R69-R83) [[6]](diffhunk://#diff-8915782f096b5bc75054300aa7240a7b18b4b40a97c5cf3f79edb8530b892932R242-R245) [[7]](diffhunk://#diff-8915782f096b5bc75054300aa7240a7b18b4b40a97c5cf3f79edb8530b892932R258) [[8]](diffhunk://#diff-8915782f096b5bc75054300aa7240a7b18b4b40a97c5cf3f79edb8530b892932R269-R280) [[9]](diffhunk://#diff-8915782f096b5bc75054300aa7240a7b18b4b40a97c5cf3f79edb8530b892932R314-R319)

### Option Parsing:
* Updated `OptionParser` to include `babsr` as a valid branching strategy.
* Modified `Options::getDivideStrategy()` to handle the new `babsr-heuristic` strategy.

### Testing:
* Added a new unit test file for Test_BaBsrSplitting.h for unit tests of the branching strategy.

2024-12-16 02:57 UTC, MatthewDaggitt commented
I think the new option should be documented in the CHANGELOG.md file?

2024-12-17 21:44 UTC, liamjdavis commented
Done!

2025-01-09 17:22 UTC, wu-haoze requested changes
Overall it looks good. I just have some comments regarding efficiency and style.

2025-01-09 17:22 UTC, wu-haoze commented on src/engine/ReluConstraint.h
> +    static std::unordered_map<const ReluConstraint *, double> _biasCache;
Actually, I think since the information is stored per ReLU, the _biasCache should just be a double, which represents the bias of the current ReLU. Otherwise, we are storing a Map like this in every ReLU.

2025-01-10 08:50 UTC, liamjdavis commented on src/nlr/NetworkLevelReasoner.cpp
> +NetworkLevelReasoner::getPrevBiasForReluConstraint( const ReluConstraint *reluConstraint ) const
Fixed!

2025-01-10 08:50 UTC, liamjdavis commented on src/engine/ReluConstraint.cpp
> +std::unordered_map<const ReluConstraint *, double> ReluConstraint::_biasCache;
Fixed!

2025-01-10 08:51 UTC, liamjdavis commented on src/engine/ReluConstraint.h
> +    static std::unordered_map<const ReluConstraint *, double> _biasCache;
I made the switch to storing it as a double instead of a Map.

2025-01-10 08:51 UTC, liamjdavis commented on src/nlr/tests/Test_NetworkLevelReasoner.h
> +    void testGetReluBias()
Fixed!

2025-01-10 08:52 UTC, liamjdavis commented
I made the requested changes, and ended up switching to saving bias as a double instead of a Map.

2025-01-12 20:08 UTC, liamjdavis commented
I made an optimization to getPreviousBias() where all the NLR iterates over all the constraints the first time getPreviousBias() is called and stores all the previous biases in a map in the NLR. Then whenever getPreviousBias() it pulls the previous bias from the map instead of iterating over all the constraints again.

2025-01-21 16:47 UTC, wu-haoze approved these changes
Just one additional minor comment. Otherwise, LGTM!

2025-01-21 16:47 UTC, wu-haoze commented on src/configuration/OptionParser.cpp
> +        "(earliest-relu/pseudo-impact/largest-interval/relu-violation/polarity/babsr-heuristic)."
rename to babsr

2025-01-22 17:48 UTC, liamjdavis commented on src/configuration/OptionParser.cpp
> +        "(earliest-relu/pseudo-impact/largest-interval/relu-violation/polarity/babsr-heuristic)."
Fixed!

2025-02-11 20:42 UTC, merged